### ISSUE TITLE
UI > the Back button design

### ISSUE THREAD

**Issue by tlle14** [TwakeApp/Mobile#222] opened 2021-01-22 09:56 UTC
# Actual Result
Recently, there are two kinds of the back button `<-` and `<`

![image](https://user-images.githubusercontent.com/69950655/105476002-a8cfa480-5cd2-11eb-9d75-e49c37c4fe8e.png)

![image](https://user-images.githubusercontent.com/69950655/105656653-46a2b980-5ef5-11eb-94a6-732bf04397dc.png)

# Expected Result
We should display 1 kind of back button.
It should be the one in our design
![image](https://user-images.githubusercontent.com/69950655/105475814-68702680-5cd2-11eb-8aed-b0bde7f4c964.png)

# Environment
Android app
Build version: twake-2-2-0

**Comment by bobs4462** [comment] 2021-01-22 12:01
@BastiaanVanGaalen Should we stick to old design, or keep using yours?

**Comment by RockinPaul** [comment] 2021-01-22 12:50
Now it looks like this: ![Simulator Screen Shot - iPhone 12 Pro Max - 2021-01-22 at 15.47.58.png](https://images.zenhubusercontent.com/5ffc24a2a62ff7cf134e10b3/2580781d-6e13-455b-aec9-7e902549b025)![Simulator Screen Shot - iPhone 12 Pro Max - 2021-01-22 at 15.48.18.png](https://images.zenhubusercontent.com/5ffc24a2a62ff7cf134e10b3/52144b1c-8b83-442e-b380-1c31c7f78fd4)

Arrow is removed from the case of modal transition, for obvious reasons.

**Comment by tlle14** [comment] 2021-01-25 03:09
Thank @RockinPaul for the improvement.
I've updated the image in the description.

**Comment by BastiaanVanGaalen** [comment] 2021-01-25 13:40
@RockinPaul confirmed, thank you!

**Comment by tlle14** [comment] 2021-01-26 02:23
Hello @RockinPaul 
Please don't close the issue. I need it open for retesting. 
If you think the issue is not a bug, convince me to close (Comment then assign to the Review/QA column)

Thanks for your collaboration!

**Comment by RockinPaul** [comment] 2021-01-26 08:27
Hello @tlle14 

Sorry, but I have no time to convince you since @BastiaanVanGaalen has already confirmed it. The issue has nothing to do with any kind of failure at all because the implementation was compliant with mockups provided by @BastiaanVanGaalen from the start, and the issue has been created by you without checking these mockups.

**Comment by tlle14** [comment] 2021-01-26 08:46
Hi @RockinPaul ,
This issue is about using a consistent design of the back button (`<` or `<-`) when comparing the actual one and the mockup design. 
If you know the creating channel mockup, please send me to verify. I don't see the design on xd.adobe.com. 

cc: @bobs4462 @BastiaanVanGaalen

**Comment by PokoinikRWS** [comment] 2021-01-26 10:50
Let use one style. 
It's not a show stopper, design will be changed soon. Lets focus on functionality.

**Comment by BastiaanVanGaalen** [comment] 2021-01-26 10:55
@tlle14 Hi there, as for consistency compliance i will keep track of all inconsistent parts of the app so no worries. As soon we have somehow stable version of the app with all functional units working properly it will become more reasonable to focus on UI consistency.
Moreover, it will be totally overhauled in a near future.

For now I beg you to keep focus on functionality and error handling rather than UI consistency. I truly appreciate your active participation in UI part but now we are running out of time to deliver the product itself and some minor detail fixing and UI fine-tuning that are non-relevant to core functionality might serve as a distractor especially given our constrained development team resource (1 member to be frank).

Hope for your understanding of our current priorities and constrains)😊

**Comment by hieuhoang998** [comment] 2021-01-29 04:11
Hi, This issue is ok, so I close this. 
Thank you

**Closed** 2021-01-29 04:11 UTC
Labels: Low, UI, bug
