### ISSUE TITLE
Message > Tapping to "show more" button will jump to the end of the message 

### ISSUE THREAD

**Issue by tlle14** [TwakeApp/Mobile#95] opened 2020-12-15 08:09 UTC
# Precondition
A long message as a paragraph

# Actual result
When tap to "show more" button, it will jump to the end of the expanded message.
https://streamable.com/sqfb2q

# Expected result
It should stay at a place user tap "show more" button

# Environment
app-release[2020-12-14]

**Comment by RockinPaul** [comment] 2021-01-22 11:51
We decided to get rid of collapsable messages because it violates the basic principles of a messenger. People have a conversation to express their thoughts to each other - that means they wanted to be heard. We do not suppose someone to treat someone's message without attention by not unwrapping it. Because chat message is not the same as social network post.

However, I wanted to make a remark on this issue anyway, due to the technical debt:

- The Feed of any social network (Facebook/Instagram/Reddit you name it...) loads on the scroll from the top. That's why messages are loading from the bottom of the screen and we get expected behavior - in case of unwrapping collapsed messages content populates in a top-down manner.

- In messenger we have a reversed list of messages and scroll it from the very bottom, that's why unwrapping, technically, will not work as you expect, unless we allocate a special content offset from the bottom giving a scroll view enough space to populate data down without moving a viewport, which seems to be a pretty custom solution to implement.

But it doesn't matter anymore if we will not decide to implement collapsable behavior for media attachments which could make sense.

Now I'm closing this issue.

**Closed by RockinPaul** 2021-01-22 11:51 UTC
Labels: Medium, bug
